name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFRONT_ENABLED: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID != '' }}

    steps:
      # 1. 檢出 (checkout) 專案程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 設定 Node.js 版本
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # 3. 安裝依賴
      - name: Install dependencies
        run: npm install

      # 4. 建置 & 匯出靜態檔案 (out/)
      - name: Build & Export
        run: |
          npm run build
          npm run export

      # 5. 設定 AWS 認證
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. 部署到 S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }} --delete

      # 7. 失效 CloudFront (如果使用 CloudFront)
      - name: Invalidate CloudFront (if using CloudFront)
        if: env.CLOUDFRONT_ENABLED == 'true'
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
